version: '3.8'

services:
  pubsub-emulator:
    image: google/cloud-sdk:emulators
    container_name: pubsub-emulator
    ports:
      - "8085:8085"
    command: /bin/bash -c "gcloud beta emulators pubsub start --project=test-project-id --host-port='0.0.0.0:8085'"
